name: churchapp_flutter
description: My ChurchApp Project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.0+35

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  fast_i18n: ^5.11.0
  easy_dialog: ^1.1.0
  sqflite: ^2.0.2
  dio: ^5.4.3+1
  provider: ^6.0.2
  transparent_image: ^2.0.0
  pull_to_refresh: ^2.0.0
  cached_network_image: ^3.2.0
  font_awesome_flutter: ^10.1.0
  line_awesome_flutter: ^3.0.1
  better_player_plus: ^1.0.7
  youtube_player_flutter_quill: ^8.2.2
  #youtube_player_flutter: ^9.0.1
  firebase_core: ^2.3.0
  firebase_messaging: ^14.1.3
  flutter_local_notifications: ^17.1.2
  shared_preferences: ^2.0.15
  email_validator: "^2.0.1"
  shimmer: ^3.0.0
  #audiofileplayer: ^2.1.1
  just_audio: ^0.9.38
  just_audio_background: ^0.0.1-beta.12
  palette_generator: ^0.3.3
  file_utils: ^1.0.0
  permission_handler: ^11.3.1
  path_provider: ^2.0.9
  isolated_download_manager: ^1.0.2
  in_app_purchase: ^3.0.8
  share_plus: ^9.0.0
  package_info: ^2.0.2
  in_app_review: ^2.0.4
  flutter_web_browser: "^0.17.1"
  lottie: ^3.1.2
  flutter_widget_from_html: ^0.15.0
  carousel_slider: ^4.2.1
  select_dialog: ^2.0.0
  #flutter_tts: ^3.2.2
  clipboard: ^0.1.3
  #translator: ^0.1.7
  flutter_sticky_header: ^0.6.1
  flutter_material_color_picker: ^1.1.0+2
  #dynamic_text_highlighting: ^2.2.0
  #media_picker_widget: ^0.0.7
  flutter_absolute_path:
    git:
      url: https://github.com/canewsin/flutter_absolute_path.git
  smooth_page_indicator: ^1.0.0+2
  visibility_detector: ^0.4.0+2
  file_picker: ^8.0.3
  event_bus: ^2.0.0
  photo_view: ^0.15.0
  #vimeoplayer_trinity: ^0.1.9
  flutter_quill: ^9.5.3
  intl: ^0.19.0
  flash: ^3.1.0
  highlight_text: ^1.3.0
  drop_cap_text: ^1.1.3
  flutter_cupertino_datetime_picker: ^3.0.0
  http_auth:
  webview_flutter: ^4.8.0
  table_calendar: ^3.0.3
  #wakelock: ^0.2.1+1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4
  collection: ^1.15.0-nullsafety.4
  flutter_animate: ^4.5.0
  intl_phone_field: ^3.2.0
  google_nav_bar: ^5.0.6
  flutter_svg: ^2.0.10+1
  flutter_arc_text: ^0.6.0
  video_player: ^2.9.1
  chewie: ^1.8.1
  flutter_dotenv: ^5.1.0
  audioplayers: ^6.0.0
  infinite_scroll_pagination: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  flutter_launcher_icons: ^0.13.1


dependency_overrides:
  #wakelock_windows: ^0.2.1
  #package_info_plus: ^8.0.0
  #win32: "5.0.0"
  #win32_registry: "1.1.0"
  #uuid: ^3.0.1
  #intl: ^0.18.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/new/mvp.jpeg"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/new/
    - assets/lottie/
    - .env

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-Regular.ttf
        - asset: assets/fonts/WorkSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/WorkSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/WorkSans-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 400

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

